// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Pills(Props) {
  return React.createElement("div", undefined);
}

var make = Pills;

exports.make = make;
/* react Not a pure module */
