// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pill$ReactHooksTemplate = require("./Pill.bs.js");

function Pills(Props) {
  var onClick = Props.onClick;
  var elements = Belt_List.toArray(Belt_List.map(/* :: */[
            /* All */2,
            /* :: */[
              /* Museum */0,
              /* :: */[
                /* Cafe */1,
                /* [] */0
              ]
            ]
          ], (function (filter) {
              return React.createElement(Pill$ReactHooksTemplate.make, {
                          name: filter,
                          onClick: onClick
                        });
            })));
  return React.createElement("div", undefined, elements);
}

var make = Pills;

exports.make = make;
/* react Not a pure module */
