// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Pill(Props) {
  var name = Props.name;
  var onClick = Props.onClick;
  return React.createElement("div", {
              onClick: onClick
            }, name);
}

var make = Pill;

exports.make = make;
/* react Not a pure module */
