// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Place(Props) {
  var name = Props.name;
  return React.createElement("p", undefined, name);
}

var make = Place;

exports.make = make;
/* react Not a pure module */
