// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Data$ReactHooksTemplate = require("./Data.bs.js");
var Form$ReactHooksTemplate = require("./Form.bs.js");
var Pills$ReactHooksTemplate = require("./Pills.bs.js");
var Place$ReactHooksTemplate = require("./Place.bs.js");

function Places(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var searchTerm = match[0];
  var match$1 = React.useState((function () {
          return /* All */2;
        }));
  var setVisibilityFilter = match$1[1];
  var handleClickVisibilityFilter = function (selectedVisibilityFilter) {
    return Curry._1(setVisibilityFilter, (function (param) {
                  return selectedVisibilityFilter;
                }));
  };
  return React.createElement("div", undefined, React.createElement(Form$ReactHooksTemplate.make, {
                  onChange: match[1],
                  searchTerm: searchTerm
                }), React.createElement(Pills$ReactHooksTemplate.make, {
                  onClick: handleClickVisibilityFilter
                }), React.createElement("ul", undefined, Belt_List.toArray(Belt_List.map(Data$ReactHooksTemplate.searchPlacesByCategory(Data$ReactHooksTemplate.searchPlacesByTerm(Data$ReactHooksTemplate.places, searchTerm), match$1[0]), (function (place) {
                            return React.createElement("li", {
                                        key: place[/* id */0]
                                      }, React.createElement(Place$ReactHooksTemplate.make, {
                                            name: place[/* name */1],
                                            placeType: place[/* placeType */8]
                                          }));
                          })))));
}

var make = Places;

exports.make = make;
/* react Not a pure module */
